#!/bin/sh
#
#   shellcheck disable=SC2086 disable=SC2046 disable=SC2015
#

trap 'pkill -2 -P $(cat /tmp/rec-pid)' 15 2

print() { printf "%b\n" "$@"; }

m() {
	menu -i "$@"
}

# exit if X isn't running
[ ! "$DISPLAY" ] &&
	print "Can't open display; exiting" && exit

# output file, use $REC_DIR and $REC_FILE if they are set
output="${REC_DIR:-$PWD}/${REC_FILE:-rec-$(date '+%Y-%m-%d_%H-%M-%S').mp4}"

# find default audio device
audio() {
	pacmd="$(pacmd list-sources | grep -i -B 1 output)"
	dev="$(echo "$pacmd" | grep -i '\* index' ||
		echo "$pacmd" | grep -i 'index' | head -n 1)"
	audio="-f pulse -i $(echo "$dev" | grep -o '[0-9]\+')"
}

help() {
	cat << EOF
Options
 -s    save the recording
 -h    display this message
 -c    skip the confirm start message
 -p  ? save and load settings from profile
 -r  ? framerate
 -b  ? force bitrate  (in MB)
 -m  ? force method   (crud, boox, display)
 -d  ? force display
 -n    disable NVENC for unsupported nvidia cards
 -a    Record desktop audio

? = Option requires another argument

Variables
 REC_DIR: If unset, saves in the current directory
 REC_FILE: If unset, saves as 'rec-\$(date '+%Y-%m-%d_%H-%M-%S').mp4'

Dependencies
 github.com/pockata/mmutils | getting info about displays
AND / OR
 github.com/ix/crud         | selecting an area
 github.com/BanchouBoo/boox | selecting an area

 ffmpeg
 dmenu (or a clone) (with the binary name 'menu')
EOF
}

while [ "$1" ]; do
	case "$1" in
		-h|--help) help;   exit;;
		-s) pkill -x rec;  exit;;
		-a) audio;;
		-c) ready="yes";;
		-p) profile="$2";  shift;;
		-m) method="$2";   shift;;
		-r) rate="$2";     shift;;
		-n) nvenc=" ";;
		-d) display="$2" method="display";  shift;;
		-b) bitrate="-b:v ${2}M";           shift;;
		--)	[ "$2" ] && output="$2";        break;;
		-*) print "Invalid option '$1'";     exit;;
		*)  output="$1";   break;;
	esac
	shift
done

[ "$REC_DIR" ] &&
	mkdir -p "$REC_DIR"

[ -f /tmp/rec-pid ] && notify-send "rec is already running, exiting." && exit


# load profile
if [ "$profile" ]; then
	mkdir -p "${XDG_CONFIG_HOME:-~/.config}/rec" >/dev/null 2>&1
	profile_location="${XDG_CONFIG_HOME:-~/.config}/rec/rec-profile-$profile"
	[ -f "$profile_location" ] && . "$profile_location"
fi



if [ ! "$method" ]; then
	# Check if the user has crud and mmutils
	command -v crud  >/dev/null 2>&1 && s=s
	command -v boox  >/dev/null 2>&1 && s=s
	command -v mattr >/dev/null 2>&1 && d=d

	# if the user only has crud or mmutils (But not both) use that
	[ "$s" ] && method=selection
	[ "$d" ] && method=display

	# if the user has both crud and mmutils ask the user which one to use
	[ "$s" ] && [ "$d" ] &&
		method="$(print "display\nselection" | m -p "Method of recording")"
fi
case $method in
	display)
		# get information about the screen
		lsm="$(lsm)"

		# if there's only one display, use that and skip asking
		if [ $(print "$lsm" | wc -l) = 1 ]; then
			display="$lsm"
		else  # if there are other displays ask the user which one to use
			[ ! "$display" ] && display="$(print "$lsm" | m -p "Display to record")"
		fi

		# get information about the display
		set -- $(mattr whxy "$display")
		width="$1"
		height="$2"
		offX="$3"
		offY="$4"
	;;
	crud|boox|selection)
		# select an area and make each number a separate word
		if command -v boox; then
			eval "$(boox 'W=%w\nH=%h\nX=%x\nY=%y')"
		else
			eval "$(crud)"
		fi

		# get information about the display
		width="$W"
		height="$H"
		offX="$X"
		offY="$Y"

		[ "$((  width % 2 ))" = 1 ] &&  width="$((  width + 1 ))"
		[ "$(( height % 2 ))" = 1 ] && height="$(( height + 1 ))"
	;;
	*)
		print "Invalid method; exiting"
	;;
esac



# prompt for framerate
[ ! "$rate" ] && rate="$(print "30\n60" | m -p "Framerate")"

# save profile
if [ "$profile" ]; then
	cat << EOF > "$profile_location"
${bitrate:+bitrate="$bitrate"}
${display:+display="$display"}
${rate:+rate="$rate"}
method="$method"
EOF
fi

# detect if the user has a nvidia card and use nvenc
[ ! "$nvenc" ] && lspci | grep -qi nvidia &&
	nvenc="-vcodec h264_nvenc"


# confirm starting the recording
[ ! "$ready" ] && ready="$(print "yes\nno" | m -p "Start the recording")"

if [ "$ready" = yes ]; then
	notify-send -t 1500 "Recording Started"

	echo $$ > /tmp/rec-pid

	ffmpeg                         \
	  -loglevel error              \
	  -y                           \
	  $audio                       \
	  -f x11grab                   \
	  -draw_mouse 1                \
	  -s "${width}x$height"        \
	  -r "$rate"                   \
	  -i "$DISPLAY.0+$offX,$offY"  \
	  $bitrate                     \
	  -pix_fmt yuv420p             \
	  $nvenc                       \
	  -q:v 0                       \
	  "$output"

	rm /tmp/rec-pid
	notify-send -t 2000 "Recording Stopped"
fi
